# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
    {:hostname => 'master-1', :ip => '192.168.70.10', :ram => 1024, :cpus => 1},
    {:hostname => 'master-2', :ip => '192.168.70.11', :ram => 1024, :cpus => 1},
    {:hostname => 'worker-1', :ip => '192.168.70.15', :ram => 1024, :cpus => 1},
    {:hostname => 'worker-2', :ip => '192.168.70.16', :ram => 1024, :cpus => 1},
    {:hostname => 'loadbalancer', :ip => '192.168.70.20', :ram => 1024, :cpus => 1},
    {:hostname => 'influxDB', :ip => '192.168.70.21', :ram => 1024, :cpus => 1},
]

Vagrant.configure("2") do |config|
    # Always use Vagrant's insecure key
    config.ssh.insert_key = false
    # Forward ssh agent to easily ssh into the different machines
    config.ssh.forward_agent = true
    # Provision nodes
    nodes.each do |node|
      config.vm.define node[:hostname] do |nodeconfig|
        nodeconfig.vm.box = "bento/ubuntu-20.04";
        nodeconfig.vm.hostname = node[:hostname] + ".box"
        nodeconfig.vm.network :private_network, ip: node[:ip]
        memory = node[:ram] ? node[:ram] : 1024;
        cpus = node[:cpus] ? node[:cpus] : 1;
        nodeconfig.vm.provider :virtualbox do |vb|
          vb.customize [
            "modifyvm", :id,
            "--memory", memory.to_s,
            "--cpus", cpus.to_s
          ]
        end
      end
    end
    # In addition, influxDB is the Ansible server
    config.vm.define "influxDB" do |ansible|
      # Provision Ansible playbook
      ansible.vm.provision "file", source: "../Ansible", destination: "$HOME"
      # Install Ansible and configure nodes
      ansible.vm.provision "shell", path: "ansible.sh"
    end
  end